import { Product } from "./types";

export const STATIC_PRODUCTS: Record<string, Product[]> = {
  bestsellers: [
    {
      "_id": "6837f9ab571e0fa754eb5c10",
      "id": 2067872,
      "sku": "3004",
      "en_name": "Camera Module OV7670",
      "ar_name": "وحدة كاميرا OV7670",
      "en_description": "Camera Module OV7670 for image capture and processing.",
      "ar_description": "وحدة كاميرا OV7670 لالتقاط الصور ومعالجتها.",
      "en_long_description": "Low-cost image sensor for Arduino and Raspberry Pi.",
      "ar_long_description": "حساس صور منخفض التكلفة لأردوينو وراسبيري باي.",
      "en_main_category": "Modules",
      "ar_main_category": "الوحدات",
      "en_category": "Camera",
      "ar_category": "كاميرات",
      "price": 3.5,
      "image": "https://zfloos-production-storage.s3.eu-central-1.amazonaws.com/public/upload/companies/4247/products/61735210162676d34b2988340_46640577.jpg,https://zfloos-production-storage.s3.eu-central-1.amazonaws.com/public/upload/companies/4247/products/91735210163676d34b3633f88_70395771.jpg,https://zfloos-production-storage.s3.eu-central-1.amazonaws.com/public/upload/companies/4247/products/91735210164676d34b41194d0_27324765.jpg",
      "quantity_on_hand": 100,
      "sold_quantity": 215,
      "visible_in_catalog": 1,
      "visible_in_search": 1,
      "slug_url": "camera-module-ov7670",
      "en_brand": "Generic",
      "ar_brand": "عام",
      "ave_cost": 0
    },
    {
      "_id": "6837f9ab571e0fa754eb5c61",
      "id": 2065630,
      "sku": "6003",
      "en_name": "Flame Sensor",
      "ar_name": "حساس اللهب",
      "en_description": "Detects flame presence using IR detection.",
      "ar_description": "يكشف وجود اللهب باستخدام الأشعة تحت الحمراء.",
      "en_long_description": "Used for fire detection systems and experiments.",
      "ar_long_description": "يستخدم في أنظمة كشف الحرائق والتجارب.",
      "en_main_category": "Sensors",
      "ar_main_category": "حساسات",
      "en_category": "Fire",
      "ar_category": "نار",
      "price": 1.2,
      "image": "https://zfloos-production-storage.s3.eu-central-1.amazonaws.com/public/upload/companies/4247/products/11735061605676af065b381d9_59285621.jpg,https://zfloos-production-storage.s3.eu-central-1.amazonaws.com/public/upload/companies/4247/products/41735061606676af066b3b5d3_93632648.jpg",
      "quantity_on_hand": 95,
      "sold_quantity": 180,
      "visible_in_catalog": 1,
      "visible_in_search": 1,
      "slug_url": "flame-sensor",
      "en_brand": "Generic",
      "ar_brand": "عام",
      "ave_cost": 0.9
    },
    {
      "_id": "6837f9ab571e0fa754eb5d1b",
      "id": 2064678,
      "sku": "11004",
      "en_name": "Keyboard With Trackpad For Raspberry Pi",
      "ar_name": "لوحة مفاتيح مع تتبع لـ Raspberry Pi",
      "en_description": "Compact keyboard with built-in trackpad.",
      "ar_description": "لوحة مفاتيح صغيرة بها لوحة تتبع مدمجة.",
      "en_long_description": "Ideal for Raspberry Pi and embedded projects.",
      "ar_long_description": "مثالي لـ Raspberry Pi والمشاريع المدمجة.",
      "en_main_category": "Peripherals",
      "ar_main_category": "ملحقات",
      "en_category": "Keyboard",
      "ar_category": "لوحة مفاتيح",
      "price": 10.9,
      "image": "https://zfloos-production-storage.s3.eu-central-1.amazonaws.com/public/upload/companies/4247/products/6173495405867694c4aed15c8_83358393.jpg",
      "quantity_on_hand": 80,
      "sold_quantity": 155,
      "visible_in_catalog": 1,
      "visible_in_search": 1,
      "slug_url": "raspberry-keyboard-trackpad",
      "en_brand": "LogiTech",
      "ar_brand": "لوجيتك",
      "ave_cost": 8.5
    },
    {
      "_id": "6837f9ab571e0fa754eb5bfd",
      "id": 2067893,
      "sku": "23003",
      "en_name": "Wireless Charger Tx/Rx Module",
      "ar_name": "وحدة شحن لاسلكي Tx/Rx",
      "en_description": "Module for wireless energy transmission.",
      "ar_description": "وحدة لنقل الطاقة لاسلكياً.",
      "en_long_description": "5V to 12V wireless transmission module.",
      "ar_long_description": "وحدة إرسال لاسلكي للطاقة من 5 إلى 12 فولت.",
      "en_main_category": "Power",
      "ar_main_category": "طاقة",
      "en_category": "Wireless Charging",
      "ar_category": "شحن لاسلكي",
      "price": 4.75,
      "image": "https://zfloos-production-storage.s3.eu-central-1.amazonaws.com/public/upload/companies/4247/products/91735211782676d3b0618ce22_54038311.jpg,https://zfloos-production-storage.s3.eu-central-1.amazonaws.com/public/upload/companies/4247/products/71735211782676d3b06afad91_46265732.jpg",
      "quantity_on_hand": 90,
      "sold_quantity": 135,
      "visible_in_catalog": 1,
      "visible_in_search": 1,
      "slug_url": "wireless-charger-module",
      "en_brand": "Generic",
      "ar_brand": "عام",
      "ave_cost": 3.8
    },
    {
      "_id": "6837f9ab571e0fa754eb5c9e",
      "id": 2065527,
      "sku": "9011",
      "en_name": "IC Socket-14Pin",
      "ar_name": "مقبس IC 14 دبوس",
      "en_description": "Socket for IC with 14 pins.",
      "ar_description": "مقبس لشريحة IC بعدد 14 دبوس.",
      "en_long_description": "Protects ICs from heat damage during soldering.",
      "ar_long_description": "يحمي شرائح IC من تلف الحرارة أثناء اللحام.",
      "en_main_category": "Connectors",
      "ar_main_category": "موصلات",
      "en_category": "IC Socket",
      "ar_category": "مقابس IC",
      "price": 0.25,
      "image": "https://zfloos-production-storage.s3.eu-central-1.amazonaws.com/public/upload/companies/4247/products/21735054938676ad65a7137e9_49152257.jpg,https://zfloos-production-storage.s3.eu-central-1.amazonaws.com/public/upload/companies/4247/products/41735054938676ad65af0ecf4_51422220.jpg",
      "quantity_on_hand": 200,
      "sold_quantity": 230,
      "visible_in_catalog": 1,
      "visible_in_search": 1,
      "slug_url": "ic-socket-14pin",
      "en_brand": "Generic",
      "ar_brand": "عام",
      "ave_cost": 0.15
    },
    {
      "_id": "6837f9ab571e0fa754eb5d2a",
      "id": 2063529,
      "sku": "06",
      "en_name": "Arduino Uno R3 SMD",
      "ar_name": "Arduino Uno R3 SMD",
      "en_description": "Arduino Uno R3 SMD",
      "ar_description": "Arduino Uno R3 SMD",
      "en_long_description": "<p class=\"MsoNormal\"><span style=\"font-size: 12.0pt; line-height: 107%; font-family: 'Arial',sans-serif; mso-ascii-theme-font: minor-bidi; mso-hansi-theme-font: minor-bidi; mso-bidi-font-family: Arial; mso-bidi-theme-font: minor-bidi; color: #404040; background: white;\">Arduino Uno R3 SMD</span></p>",
      "ar_long_description": "<p class=\"MsoNormal\"><span style=\"font-size: 12.0pt; line-height: 107%; font-family: 'Arial',sans-serif; mso-ascii-theme-font: minor-bidi; mso-hansi-theme-font: minor-bidi; mso-bidi-font-family: Arial; mso-bidi-theme-font: minor-bidi; color: #404040; background: white;\">Arduino Uno R3 SMD</span></p>",
      "en_main_category": "Arduino",
      "ar_main_category": "Arduino",
      "en_category": "Arduino",
      "ar_category": "Arduino",
      "price": 3,
      "image": "https://zfloos-production-storage.s3.eu-central-1.amazonaws.com/public/upload/companies/4247/products/6173488871467684d0a2aa7b3_73076497.jpg,https://zfloos-production-storage.s3.eu-central-1.amazonaws.com/public/upload/companies/4247/products/4173488871467684d0ab33944_99251804.jpg,https://zfloos-production-storage.s3.eu-central-1.amazonaws.com/public/upload/companies/4247/products/9173488871567684d0b96e1c1_80729184.jpg",
      "quantity_on_hand": 0,
      "sold_quantity": 0,
      "visible_in_catalog": 1,
      "visible_in_search": 1,
      "slug_url": "https://amtronics.co/products/arduino-uno-r3-smd-2063529",
      "discount": 0,
      // "discount_type": null,
      // "ar_brand": null,
      // "en_brand": null,
      "ave_cost": 0
    },
    {
      "_id": "2091112",
      "id": 2091112,
      "sku": "2011",
      "en_name": "Box for Components",
      "ar_name": "علبة مكونات",
      "en_description": "Plastic box with compartments for small parts.",
      "ar_description": "علبة بلاستيكية بها فواصل للأجزاء الصغيرة.",
      "en_long_description": "Organize resistors, capacitors and ICs.",
      "ar_long_description": "لتنظيم المقاومات والمكثفات والدوائر المتكاملة.",
      "en_main_category": "Storage",
      "ar_main_category": "تخزين",
      "en_category": "Organizer",
      "ar_category": "منظم",
      "price": 1.5,
      "image": "/placeholder.svg",
      "quantity_on_hand": 150,
      "sold_quantity": 160,
      "visible_in_catalog": 1,
      "visible_in_search": 1,
      "slug_url": "component-box",
      "en_brand": "Generic",
      "ar_brand": "عام",
      "ave_cost": 1
    },
    {
      "_id": "2091113",
      "id": 2091113,
      "sku": "2022",
      "en_name": "Soldering Iron 60W",
      "ar_name": "كاوية لحام 60 واط",
      "en_description": "Basic soldering iron for electronics work.",
      "ar_description": "كاوية لحام أساسية لأعمال الإلكترونيات.",
      "en_long_description": "Comes with standard tip and fast heating coil.",
      "ar_long_description": "مزودة برأس قياسي وسخان سريع.",
      "en_main_category": "Tools",
      "ar_main_category": "أدوات",
      "en_category": "Soldering",
      "ar_category": "لحام",
      "price": 4.2,
      "image": "/placeholder.svg",
      "quantity_on_hand": 65,
      "sold_quantity": 140,
      "visible_in_catalog": 1,
      "visible_in_search": 1,
      "slug_url": "soldering-iron-60w",
      "en_brand": "QuickHeat",
      "ar_brand": "كويك هيت",
      "ave_cost": 3.5
    },
    {
      "_id": "6837f9ab571e0fa754eb5c2f",
      "id": 2091114,
      "sku": "12019",
      "en_name": "LCD 20x4 i2C",
      "ar_name": "شاشة LCD 20x4 i2C",
      "en_description": "20x4 character LCD with i2C interface.",
      "ar_description": "شاشة عرض 20x4 بالأحرف تدعم واجهة i2C.",
      "en_long_description": "Ideal for Arduino and Raspberry Pi displays.",
      "ar_long_description": "مثالية لمشاريع العرض باستخدام أردوينو.",
      "en_main_category": "Displays",
      "ar_main_category": "شاشات",
      "en_category": "LCD",
      "ar_category": "شاشات LCD",
      "price": 4.9,
      "image": "https://zfloos-production-storage.s3.eu-central-1.amazonaws.com/public/upload/companies/4247/products/81735205603676d22e3095cf0_61139857.jpg,https://zfloos-production-storage.s3.eu-central-1.amazonaws.com/public/upload/companies/4247/products/01735205601676d22e1b26737_55137842.jpg,https://zfloos-production-storage.s3.eu-central-1.amazonaws.com/public/upload/companies/4247/products/91735205600676d22e0f03a71_29334887.jpg,https://zfloos-production-storage.s3.eu-central-1.amazonaws.com/public/upload/companies/4247/products/11735205602676d22e26d3935_54470013.jpg",
      "quantity_on_hand": 75,
      "sold_quantity": 175,
      "visible_in_catalog": 1,
      "visible_in_search": 1,
      "slug_url": "lcd-20x4-i2c",
      "en_brand": "DisplayTech",
      "ar_brand": "ديسبلايتك",
      "ave_cost": 3.6
    },
    {
      "_id": "6837f9ab571e0fa754eb5c75",
      "id": 2091115,
      "sku": "6005",
      "en_name": "Force Sensor FSR406",
      "ar_name": "حساس القوة FSR406",
      "en_description": "Force sensitive resistor sensor.",
      "ar_description": "مستشعر مقاومة حساس للقوة.",
      "en_long_description": "Measures varying pressure and force inputs.",
      "ar_long_description": "لقياس الضغط والقوة المتغيرة.",
      "en_main_category": "Sensors",
      "ar_main_category": "حساسات",
      "en_category": "Force",
      "ar_category": "قوة",
      "price": 2.6,
      "image": "https://zfloos-production-storage.s3.eu-central-1.amazonaws.com/public/upload/companies/4247/products/91735059624676ae8a85e0075_37589883.jpg,https://zfloos-production-storage.s3.eu-central-1.amazonaws.com/public/upload/companies/4247/products/81735059623676ae8a7eae649_94411536.jpg",
      "quantity_on_hand": 60,
      "sold_quantity": 120,
      "visible_in_catalog": 1,
      "visible_in_search": 1,
      "slug_url": "force-sensor-fsr406",
      "en_brand": "Interlink",
      "ar_brand": "انترلينك",
      "ave_cost": 2.1
    }
  ],
  deals: [
    {
      "_id": "6837f9ab571e0fa754eb5ac8",
      "id": 2094102,
      "sku": "11012",
      "en_name": "Keyestudio MLX90614 Infrared Temperature Sensor",
      "ar_name": "حساس حرارة بالأشعة تحت الحمراء MLX90614",
      "en_description": "Non-contact IR temperature sensor for projects.",
      "ar_description": "حساس حرارة بالأشعة تحت الحمراء بدون تلامس.",
      "en_long_description": "Used in body temperature scanners and automation.",
      "ar_long_description": "يُستخدم في فحص حرارة الجسم والتطبيقات الآلية.",
      "en_main_category": "Sensors",
      "ar_main_category": "حساسات",
      "en_category": "Temperature",
      "ar_category": "درجة الحرارة",
      "price": 6.99,
      "image": "https://zfloos-production-storage.s3.eu-central-1.amazonaws.com/public/upload/companies/4247/products/917376172776791ef7d04a5a3_10407579.jpg,https://zfloos-production-storage.s3.eu-central-1.amazonaws.com/public/upload/companies/4247/products/817376172776791ef7d6945f7_74615826.jpg",
      "quantity_on_hand": 50,
      "sold_quantity": 84,
      "visible_in_catalog": 1,
      "visible_in_search": 1,
      "slug_url": "mlx90614-infrared-temp",
      "en_brand": "Keyestudio",
      "ar_brand": "كيي ستوديو",
      "ave_cost": 5.4
    },
    {
      "_id": "6837f9ab571e0fa754eb5c44",
      "id": 2067788,
      "sku": "IRF540",
      "en_name": "IRF540 MOSFET Transistor",
      "ar_name": "ترانزستور IRF540 MOSFET",
      "en_description": "Power MOSFET for switching applications.",
      "ar_description": "ترانزستور MOSFET للتبديل والتحكم في الطاقة.",
      "en_long_description": "N-channel MOSFET used in motors and LEDs.",
      "ar_long_description": "MOSFET من نوع N يُستخدم في المحركات والـ LEDs.",
      "en_main_category": "Components",
      "ar_main_category": "مكونات",
      "en_category": "Transistors",
      "ar_category": "ترانزستورات",
      "price": 1.1,
      "image": "https://zfloos-production-storage.s3.eu-central-1.amazonaws.com/public/upload/companies/4247/products/71735401698677020e2d84d81_80727574.jpg",
      "quantity_on_hand": 120,
      "sold_quantity": 190,
      "visible_in_catalog": 1,
      "visible_in_search": 1,
      "slug_url": "irf540-mosfet",
      "en_brand": "STMicroelectronics",
      "ar_brand": "إس تي",
      "ave_cost": 0.75
    },
    {
      "_id": "6837f9ab571e0fa754eb5b6a",
      "id": 2068393,
      "sku": "19032",
      "en_name": "Pulse Oximeter MAX30101",
      "ar_name": "جهاز نبض MAX30101",
      "en_description": "Measure pulse and oxygen saturation levels.",
      "ar_description": "لقياس نبضات القلب ونسبة الأوكسجين.",
      "en_long_description": "Used in health monitoring and biometric devices.",
      "ar_long_description": "يُستخدم في أجهزة المراقبة الصحية والقياسات الحيوية.",
      "en_main_category": "Sensors",
      "ar_main_category": "حساسات",
      "en_category": "Health",
      "ar_category": "صحة",
      "price": 8.99,
      "image": "https://zfloos-production-storage.s3.eu-central-1.amazonaws.com/public/upload/companies/4247/products/817354645436771165f72b0e2_13384994.jpg,https://zfloos-production-storage.s3.eu-central-1.amazonaws.com/public/upload/companies/4247/products/31735464544677116606870a8_45403813.jpg",
      "quantity_on_hand": 40,
      "sold_quantity": 77,
      "visible_in_catalog": 1,
      "visible_in_search": 1,
      "slug_url": "max30101-pulse-oximeter",
      "en_brand": "SparkFun",
      "ar_brand": "سبارك فن",
      "ave_cost": 6.95
    },
    {
      "_id": "6837f9ab571e0fa754eb5c22",
      "id": 2067854,
      "sku": "2006",
      "en_name": "Boost+Buck Converter Module",
      "ar_name": "وحدة رفع وخفض الجهد",
      "en_description": "DC-DC adjustable step up/down module.",
      "ar_description": "وحدة رفع/خفض جهد قابلة للتعديل.",
      "en_long_description": "Useful for battery-powered and embedded devices.",
      "ar_long_description": "مفيد للأجهزة التي تعمل بالبطارية والمشاريع المدمجة.",
      "en_main_category": "Power",
      "ar_main_category": "طاقة",
      "en_category": "Converter",
      "ar_category": "محولات",
      "price": 3.85,
      "image": "https://zfloos-production-storage.s3.eu-central-1.amazonaws.com/public/upload/companies/4247/products/4173926433467ab114e6c3e03_60195648.jpg,https://zfloos-production-storage.s3.eu-central-1.amazonaws.com/public/upload/companies/4247/products/91735208726676d2f16a11057_21552284.jpg,https://zfloos-production-storage.s3.eu-central-1.amazonaws.com/public/upload/companies/4247/products/81735208726676d2f1613bf16_67446354.jpg",
      "quantity_on_hand": 60,
      "sold_quantity": 104,
      "visible_in_catalog": 1,
      "visible_in_search": 1,
      "slug_url": "boost-buck-module",
      "en_brand": "Generic",
      "ar_brand": "عام",
      "ave_cost": 2.75
    },
    {
      "_id": "6837f9ab571e0fa754eb5c75",
      "id": 2065592,
      "sku": "6005",
      "en_name": "Force Sensor FSR406",
      "ar_name": "حساس القوة FSR406",
      "en_description": "Force sensitive resistor sensor.",
      "ar_description": "مستشعر مقاومة حساس للقوة.",
      "en_long_description": "Measures pressure and force input.",
      "ar_long_description": "لقياس الضغط والقوة.",
      "en_main_category": "Sensors",
      "ar_main_category": "حساسات",
      "en_category": "Force",
      "ar_category": "قوة",
      "price": 2.6,
      "image": "https://zfloos-production-storage.s3.eu-central-1.amazonaws.com/public/upload/companies/4247/products/91735059624676ae8a85e0075_37589883.jpg,https://zfloos-production-storage.s3.eu-central-1.amazonaws.com/public/upload/companies/4247/products/81735059623676ae8a7eae649_94411536.jpg",
      "quantity_on_hand": 90,
      "sold_quantity": 112,
      "visible_in_catalog": 1,
      "visible_in_search": 1,
      "slug_url": "force-sensor-fsr406",
      "en_brand": "Interlink",
      "ar_brand": "انترلينك",
      "ave_cost": 2.1
    },
    {
      "_id": "6837f9ab571e0fa754eb5b84",
      "id": 2068225,
      "sku": "2011",
      "en_name": "Box for Components",
      "ar_name": "علبة مكونات",
      "en_description": "Storage box for small electronics.",
      "ar_description": "صندوق تخزين للإلكترونيات الصغيرة.",
      "en_long_description": "Great for organizing resistors and ICs.",
      "ar_long_description": "ممتاز لتنظيم المقاومات والدوائر.",
      "en_main_category": "Storage",
      "ar_main_category": "تخزين",
      "en_category": "Box",
      "ar_category": "صندوق",
      "price": 1.5,
      "image": "https://zfloos-production-storage.s3.eu-central-1.amazonaws.com/public/upload/companies/4247/products/21735376389676fbe05e64cc7_30769112.jpg,https://zfloos-production-storage.s3.eu-central-1.amazonaws.com/public/upload/companies/4247/products/41735376391676fbe07233229_29104412.jpg,https://zfloos-production-storage.s3.eu-central-1.amazonaws.com/public/upload/companies/4247/products/51735376390676fbe06947437_19168949.jpg",
      "quantity_on_hand": 85,
      "sold_quantity": 143,
      "visible_in_catalog": 1,
      "visible_in_search": 1,
      "slug_url": "component-storage-box",
      "en_brand": "Generic",
      "ar_brand": "عام",
      "ave_cost": 1
    },
    {
      "_id": "6837f9ab571e0fa754eb5d16",
      "id": 2064746,
      "sku": "18021",
      "en_name": "Raspberry Pi 4 Original Charger",
      "ar_name": "شاحن راسبيري باي 4 أصلي",
      "en_description": "Power adapter for Raspberry Pi 4.",
      "ar_description": "محول طاقة لـ Raspberry Pi 4.",
      "en_long_description": "5.1V 3A official adapter with USB-C.",
      "ar_long_description": "محول رسمي بقدرة 5.1 فولت 3 أمبير.",
      "en_main_category": "Power",
      "ar_main_category": "طاقة",
      "en_category": "Charger",
      "ar_category": "شاحن",
      "price": 9.25,
      "image": "https://zfloos-production-storage.s3.eu-central-1.amazonaws.com/public/upload/companies/4247/products/4173496936867698818290d01_41805954.jpg,https://zfloos-production-storage.s3.eu-central-1.amazonaws.com/public/upload/companies/4247/products/01734969368676988188f49f7_45619102.jpg",
      "quantity_on_hand": 35,
      "sold_quantity": 93,
      "visible_in_catalog": 1,
      "visible_in_search": 1,
      "slug_url": "raspberry-charger",
      "en_brand": "Raspberry Pi",
      "ar_brand": "راسبيري باي",
      "ave_cost": 7.75
    },
    {
      "_id": "6837f9ab571e0fa754eb5af5",
      "id": 2090856,
      "sku": "2038",
      "en_name": "Battery Acid 6V-4.5Ah",
      "ar_name": "بطارية حامض 6V-4.5Ah",
      "en_description": "Lead acid rechargeable battery.",
      "ar_description": "بطارية رصاص قابلة لإعادة الشحن.",
      "en_long_description": "Used in small robots and portable circuits.",
      "ar_long_description": "يُستخدم في الروبوتات الصغيرة والدارات المحمولة.",
      "en_main_category": "Power",
      "ar_main_category": "طاقة",
      "en_category": "Battery",
      "ar_category": "بطارية",
      "price": 7.75,
      "image": "https://zfloos-production-storage.s3.eu-central-1.amazonaws.com/public/upload/companies/4247/products/11737306257678d3091746ca1_28149164.jpg,https://zfloos-production-storage.s3.eu-central-1.amazonaws.com/public/upload/companies/4247/products/31737306257678d3091eb7aa9_94982771.jpg,https://zfloos-production-storage.s3.eu-central-1.amazonaws.com/public/upload/companies/4247/products/51737306258678d309293ae47_67133829.jpg",
      "quantity_on_hand": 25,
      "sold_quantity": 61,
      "visible_in_catalog": 1,
      "visible_in_search": 1,
      "slug_url": "battery-6v-4.5ah",
      "en_brand": "Volta",
      "ar_brand": "فولتا",
      "ave_cost": 6.2
    },
    {
      "_id": "6837f9ab571e0fa754eb5bc7",
      "id": 2067979,
      "sku": "2029",
      "en_name": "Torch Bulb 3.8V",
      "ar_name": "مصباح يدوي 3.8V",
      "en_description": "Mini bulb for flashlights and electronics.",
      "ar_description": "مصباح صغير للمصابيح اليدوية والمشاريع.",
      "en_long_description": "Can be powered by a 3.7V lithium cell.",
      "ar_long_description": "يمكن تشغيله ببطارية ليثيوم 3.7V.",
      "en_main_category": "Components",
      "ar_main_category": "مكونات",
      "en_category": "Lighting",
      "ar_category": "إضاءة",
      "price": 1.9,
      "image": "https://zfloos-production-storage.s3.eu-central-1.amazonaws.com/public/upload/companies/4247/products/01735238292676da294f25850_62977393.jpg,https://zfloos-production-storage.s3.eu-central-1.amazonaws.com/public/upload/companies/4247/products/11735238293676da2957699e6_87941635.jpg",
      "quantity_on_hand": 90,
      "sold_quantity": 63,
      "visible_in_catalog": 1,
      "visible_in_search": 1,
      "slug_url": "torch-bulb-3.8v",
      "en_brand": "EverBright",
      "ar_brand": "إيفربرايت",
      "ave_cost": 1.4
    },
    {
      "_id": "6837f9ab571e0fa754eb5c85",
      "id": 2065555,
      "sku": "2033",
      "en_name": "Mini Breadboard",
      "ar_name": "لوحة اختبار صغيرة",
      "en_description": "Compact solderless breadboard.",
      "ar_description": "لوحة اختبار بدون لحام مدمجة.",
      "en_long_description": "Ideal for prototyping small circuits.",
      "ar_long_description": "مثالية لبناء الدارات الصغيرة بسرعة.",
      "en_main_category": "Prototyping",
      "ar_main_category": "النماذج",
      "en_category": "Breadboards",
      "ar_category": "لوحات اختبار",
      "price": 1.1,
      "image": "https://zfloos-production-storage.s3.eu-central-1.amazonaws.com/public/upload/companies/4247/products/91735058045676ae27d238478_94141420.jpg",
      "quantity_on_hand": 100,
      "sold_quantity": 80,
      "visible_in_catalog": 1,
      "visible_in_search": 1,
      "slug_url": "mini-breadboard",
      "en_brand": "ProtoLab",
      "ar_brand": "بروتولاب",
      "ave_cost": 0.7
    }
  ],
  
  recommended: [
    {
      "_id": "6837f9ab571e0fa754eb5d28",
      "id": 2063533,
      "sku": "18",
      "en_name": "Arduino Uno R4 Minima",
      "ar_name": "أردوينو أونو R4 مينما",
      "en_description": "Compact Arduino Uno board for embedded systems.",
      "ar_description": "لوحة أردوينو أونو صغيرة للنظم المدمجة.",
      "en_long_description": "Ideal for beginners and prototyping embedded systems.",
      "ar_long_description": "مثالية للمبتدئين والنماذج الأولية.",
      "en_main_category": "Development Boards",
      "ar_main_category": "لوحات تطوير",
      "en_category": "Arduino",
      "ar_category": "أردوينو",
      "price": 13.95,
      "image": "https://zfloos-production-storage.s3.eu-central-1.amazonaws.com/public/upload/companies/4247/products/317348910826768564a413083_14286283.jpg,https://zfloos-production-storage.s3.eu-central-1.amazonaws.com/public/upload/companies/4247/products/017348910806768564867abe3_14744371.jpg,https://zfloos-production-storage.s3.eu-central-1.amazonaws.com/public/upload/companies/4247/products/11734891081676856492bde79_42252943.jpg,https://zfloos-production-storage.s3.eu-central-1.amazonaws.com/public/upload/companies/4247/products/5173489108167685649b00a39_44933882.jpg",
      "quantity_on_hand": 35,
      "sold_quantity": 174,
      "visible_in_catalog": 1,
      "visible_in_search": 1,
      "slug_url": "arduino-uno-r4-minima",
      "en_brand": "Arduino",
      "ar_brand": "أردوينو",
      "ave_cost": 10.5
    },
    {
      "_id": "6837f9ab571e0fa754eb5c6b",
      "id": 2065605,
      "sku": "38",
      "en_name": "NodeMCU ESP8266",
      "ar_name": "نود إم سي يو ESP8266",
      "en_description": "WiFi-enabled development board.",
      "ar_description": "لوحة تطوير مزودة بالواي فاي.",
      "en_long_description": "Popular for IoT projects and smart devices.",
      "ar_long_description": "شائعة في مشاريع إنترنت الأشياء.",
      "en_main_category": "Development Boards",
      "ar_main_category": "لوحات تطوير",
      "en_category": "WiFi Boards",
      "ar_category": "لوحات واي فاي",
      "price": 5.75,
      "image": "https://zfloos-production-storage.s3.eu-central-1.amazonaws.com/public/upload/companies/4247/products/21735060514676aec22141ea8_34382249.jpg,https://zfloos-production-storage.s3.eu-central-1.amazonaws.com/public/upload/companies/4247/products/11735060514676aec22e6f625_38801915.jpg,https://zfloos-production-storage.s3.eu-central-1.amazonaws.com/public/upload/companies/4247/products/11735060515676aec23ef2104_19258887.jpg,https://zfloos-production-storage.s3.eu-central-1.amazonaws.com/public/upload/companies/4247/products/51735060516676aec24afdae1_27732798.jpg",
      "quantity_on_hand": 48,
      "sold_quantity": 198,
      "visible_in_catalog": 1,
      "visible_in_search": 1,
      "slug_url": "nodemcu-esp8266",
      "en_brand": "NodeMCU",
      "ar_brand": "نود إم سي يو",
      "ave_cost": 4
    },
    {
      "_id": "6837f9ab571e0fa754eb5d26",
      "id": 2064643,
      "sku": "08",
      "en_name": "Arduino Mega 2560",
      "ar_name": "Arduino Mega 2560",
      "en_description": "Arduino Mega 2560",
      "ar_description": "Arduino Mega 2560",
      "en_long_description": "<p class=\"MsoNormal\" style=\"line-height: normal; mso-outline-level: 2; margin: 15.0pt 0in 7.5pt 0in;\"><span style=\"font-size: 12.0pt; font-family: 'Arial',sans-serif; mso-fareast-font-family: 'Times New Roman'; color: #404040;\">Product description</span></p>\n<p class=\"MsoNormal\" style=\"margin-bottom: 7.5pt; line-height: normal;\"><span style=\"font-size: 12.0pt; font-family: 'Arial',sans-serif; mso-fareast-font-family: 'Times New Roman'; color: #404040;\">The Mega 2560 is a microcontroller board based on the ATmega2560 .It has 54 digital input/output pins (of which 14 can be used as PWM outputs), 16 analog inputs, 4 UARTs (hardware serial ports), a 16 MHz crystal oscillator, a USB connection, a power jack, an ICSP header, and a reset button. It contains everything needed to support the microcontroller; simply connect it to a computer with a USB cable or power it with a AC-to-DC adapter or battery to get started. The Mega is compatible with most shields designed for the Arduino Duemilanove or Diecimila.</span></p>\n<p class=\"MsoNormal\" style=\"margin-bottom: 7.5pt; line-height: normal;\"><span style=\"font-size: 12.0pt; font-family: 'Arial',sans-serif; mso-fareast-font-family: 'Times New Roman'; color: #404040;\">The Mega 2560 is an update to the Arduino Mega, which it replaces.</span></p>\n<p class=\"MsoNormal\" style=\"margin-bottom: 7.5pt; line-height: normal;\"><span style=\"font-size: 12.0pt; font-family: 'Arial',sans-serif; mso-fareast-font-family: 'Times New Roman'; color: #404040;\"><br /><br style=\"mso-special-character: line-break;\" /><!-- [if !supportLineBreakNewLine]--><br style=\"mso-special-character: line-break;\" /><!--[endif]--></span></p>\n<p class=\"MsoNormal\" style=\"margin-bottom: 7.5pt; line-height: normal;\"><span style=\"font-size: 12.0pt; font-family: 'Arial',sans-serif; mso-fareast-font-family: 'Times New Roman'; color: #404040;\">Microcontroller</span></p>\n<p class=\"MsoNormal\" style=\"margin-bottom: 7.5pt; line-height: normal;\"><span style=\"font-size: 12.0pt; font-family: 'Arial',sans-serif; mso-fareast-font-family: 'Times New Roman'; color: #404040;\">ATmega2560</span></p>\n<p class=\"MsoNormal\" style=\"margin-bottom: 7.5pt; line-height: normal;\"><span style=\"font-size: 12.0pt; font-family: 'Arial',sans-serif; mso-fareast-font-family: 'Times New Roman'; color: #404040;\">Operating Voltage</span></p>\n<p class=\"MsoNormal\" style=\"margin-bottom: 7.5pt; line-height: normal;\"><span style=\"font-size: 12.0pt; font-family: 'Arial',sans-serif; mso-fareast-font-family: 'Times New Roman'; color: #404040;\">5V</span></p>\n<p class=\"MsoNormal\" style=\"margin-bottom: 7.5pt; line-height: normal;\"><span style=\"font-size: 12.0pt; font-family: 'Arial',sans-serif; mso-fareast-font-family: 'Times New Roman'; color: #404040;\">Input Voltage (recommended)</span></p>\n<p class=\"MsoNormal\" style=\"margin-bottom: 7.5pt; line-height: normal;\"><span style=\"font-size: 12.0pt; font-family: 'Arial',sans-serif; mso-fareast-font-family: 'Times New Roman'; color: #404040;\">7-12V</span></p>\n<p class=\"MsoNormal\" style=\"margin-bottom: 7.5pt; line-height: normal;\"><span style=\"font-size: 12.0pt; font-family: 'Arial',sans-serif; mso-fareast-font-family: 'Times New Roman'; color: #404040;\">Input Voltage (limits)</span></p>\n<p class=\"MsoNormal\" style=\"margin-bottom: 7.5pt; line-height: normal;\"><span style=\"font-size: 12.0pt; font-family: 'Arial',sans-serif; mso-fareast-font-family: 'Times New Roman'; color: #404040;\">6-20V</span></p>\n<p class=\"MsoNormal\" style=\"margin-bottom: 7.5pt; line-height: normal;\"><span style=\"font-size: 12.0pt; font-family: 'Arial',sans-serif; mso-fareast-font-family: 'Times New Roman'; color: #404040;\">Digital I/O Pins</span></p>\n<p class=\"MsoNormal\" style=\"margin-bottom: 7.5pt; line-height: normal;\"><span style=\"font-size: 12.0pt; font-family: 'Arial',sans-serif; mso-fareast-font-family: 'Times New Roman'; color: #404040;\">54 (of which 14 provide PWM output)</span></p>\n<p class=\"MsoNormal\" style=\"margin-bottom: 7.5pt; line-height: normal;\"><span style=\"font-size: 12.0pt; font-family: 'Arial',sans-serif; mso-fareast-font-family: 'Times New Roman'; color: #404040;\">Analog Input Pins</span></p>\n<p class=\"MsoNormal\" style=\"margin-bottom: 7.5pt; line-height: normal;\"><span style=\"font-size: 12.0pt; font-family: 'Arial',sans-serif; mso-fareast-font-family: 'Times New Roman'; color: #404040;\">16</span></p>\n<p class=\"MsoNormal\" style=\"margin-bottom: 7.5pt; line-height: normal;\"><span style=\"font-size: 12.0pt; font-family: 'Arial',sans-serif; mso-fareast-font-family: 'Times New Roman'; color: #404040;\">DC Current per I/O Pin</span></p>\n<p class=\"MsoNormal\" style=\"margin-bottom: 7.5pt; line-height: normal;\"><span style=\"font-size: 12.0pt; font-family: 'Arial',sans-serif; mso-fareast-font-family: 'Times New Roman'; color: #404040;\">40 mA</span></p>\n<p class=\"MsoNormal\" style=\"margin-bottom: 7.5pt; line-height: normal;\"><span style=\"font-size: 12.0pt; font-family: 'Arial',sans-serif; mso-fareast-font-family: 'Times New Roman'; color: #404040;\">DC Current for 3.3V Pin</span></p>\n<p class=\"MsoNormal\" style=\"margin-bottom: 7.5pt; line-height: normal;\"><span style=\"font-size: 12.0pt; font-family: 'Arial',sans-serif; mso-fareast-font-family: 'Times New Roman'; color: #404040;\">50 mA</span></p>\n<p class=\"MsoNormal\" style=\"margin-bottom: 7.5pt; line-height: normal;\"><span style=\"font-size: 12.0pt; font-family: 'Arial',sans-serif; mso-fareast-font-family: 'Times New Roman'; color: #404040;\">Flash Memory</span></p>\n<p class=\"MsoNormal\" style=\"margin-bottom: 7.5pt; line-height: normal;\"><span style=\"font-size: 12.0pt; font-family: 'Arial',sans-serif; mso-fareast-font-family: 'Times New Roman'; color: #404040;\">256 KB of which 8 KB used by bootloader</span></p>\n<p class=\"MsoNormal\" style=\"margin-bottom: 7.5pt; line-height: normal;\"><span style=\"font-size: 12.0pt; font-family: 'Arial',sans-serif; mso-fareast-font-family: 'Times New Roman'; color: #404040;\">SRAM</span></p>\n<p class=\"MsoNormal\" style=\"margin-bottom: 7.5pt; line-height: normal;\"><span style=\"font-size: 12.0pt; font-family: 'Arial',sans-serif; mso-fareast-font-family: 'Times New Roman'; color: #404040;\">8 KB</span></p>\n<p class=\"MsoNormal\" style=\"margin-bottom: 7.5pt; line-height: normal;\"><span style=\"font-size: 12.0pt; font-family: 'Arial',sans-serif; mso-fareast-font-family: 'Times New Roman'; color: #404040;\">EEPROM</span></p>\n<p class=\"MsoNormal\" style=\"margin-bottom: 7.5pt; line-height: normal;\"><span style=\"font-size: 12.0pt; font-family: 'Arial',sans-serif; mso-fareast-font-family: 'Times New Roman'; color: #404040;\">4 KB</span></p>\n<p class=\"MsoNormal\" style=\"margin-bottom: 7.5pt; line-height: normal;\"><span style=\"font-size: 12.0pt; font-family: 'Arial',sans-serif; mso-fareast-font-family: 'Times New Roman'; color: #404040;\">Clock Speed</span></p>\n<p class=\"MsoNormal\" style=\"margin-bottom: 7.5pt; line-height: normal;\"><span style=\"font-size: 12.0pt; font-family: 'Arial',sans-serif; mso-fareast-font-family: 'Times New Roman'; color: #404040;\">16 MHz</span></p>\n<p class=\"MsoNormal\" style=\"margin-bottom: 7.5pt; line-height: normal;\"><span style=\"font-size: 12.0pt; font-family: 'Arial',sans-serif; mso-fareast-font-family: 'Times New Roman'; color: #404040;\"> </span></p>\n<p class=\"MsoNormal\"><span style=\"font-size: 12.0pt; line-height: 107%; font-family: 'Arial',sans-serif;\"> </span></p>",
      "ar_long_description": "<p class=\"MsoNormal\" style=\"line-height: normal; mso-outline-level: 2; margin: 15.0pt 0in 7.5pt 0in;\"><span style=\"font-size: 12.0pt; font-family: 'Arial',sans-serif; mso-fareast-font-family: 'Times New Roman'; color: #404040;\">Product description</span></p>\n<p class=\"MsoNormal\" style=\"margin-bottom: 7.5pt; line-height: normal;\"><span style=\"font-size: 12.0pt; font-family: 'Arial',sans-serif; mso-fareast-font-family: 'Times New Roman'; color: #404040;\">The Mega 2560 is a microcontroller board based on the ATmega2560 .It has 54 digital input/output pins (of which 14 can be used as PWM outputs), 16 analog inputs, 4 UARTs (hardware serial ports), a 16 MHz crystal oscillator, a USB connection, a power jack, an ICSP header, and a reset button. It contains everything needed to support the microcontroller; simply connect it to a computer with a USB cable or power it with a AC-to-DC adapter or battery to get started. The Mega is compatible with most shields designed for the Arduino Duemilanove or Diecimila.</span></p>\n<p class=\"MsoNormal\" style=\"margin-bottom: 7.5pt; line-height: normal;\"><span style=\"font-size: 12.0pt; font-family: 'Arial',sans-serif; mso-fareast-font-family: 'Times New Roman'; color: #404040;\">The Mega 2560 is an update to the Arduino Mega, which it replaces.</span></p>\n<p class=\"MsoNormal\" style=\"margin-bottom: 7.5pt; line-height: normal;\"><span style=\"font-size: 12.0pt; font-family: 'Arial',sans-serif; mso-fareast-font-family: 'Times New Roman'; color: #404040;\"><br /><br style=\"mso-special-character: line-break;\" /><!-- [if !supportLineBreakNewLine]--><br style=\"mso-special-character: line-break;\" /><!--[endif]--></span></p>\n<p class=\"MsoNormal\" style=\"margin-bottom: 7.5pt; line-height: normal;\"><span style=\"font-size: 12.0pt; font-family: 'Arial',sans-serif; mso-fareast-font-family: 'Times New Roman'; color: #404040;\">Microcontroller</span></p>\n<p class=\"MsoNormal\" style=\"margin-bottom: 7.5pt; line-height: normal;\"><span style=\"font-size: 12.0pt; font-family: 'Arial',sans-serif; mso-fareast-font-family: 'Times New Roman'; color: #404040;\">ATmega2560</span></p>\n<p class=\"MsoNormal\" style=\"margin-bottom: 7.5pt; line-height: normal;\"><span style=\"font-size: 12.0pt; font-family: 'Arial',sans-serif; mso-fareast-font-family: 'Times New Roman'; color: #404040;\">Operating Voltage</span></p>\n<p class=\"MsoNormal\" style=\"margin-bottom: 7.5pt; line-height: normal;\"><span style=\"font-size: 12.0pt; font-family: 'Arial',sans-serif; mso-fareast-font-family: 'Times New Roman'; color: #404040;\">5V</span></p>\n<p class=\"MsoNormal\" style=\"margin-bottom: 7.5pt; line-height: normal;\"><span style=\"font-size: 12.0pt; font-family: 'Arial',sans-serif; mso-fareast-font-family: 'Times New Roman'; color: #404040;\">Input Voltage (recommended)</span></p>\n<p class=\"MsoNormal\" style=\"margin-bottom: 7.5pt; line-height: normal;\"><span style=\"font-size: 12.0pt; font-family: 'Arial',sans-serif; mso-fareast-font-family: 'Times New Roman'; color: #404040;\">7-12V</span></p>\n<p class=\"MsoNormal\" style=\"margin-bottom: 7.5pt; line-height: normal;\"><span style=\"font-size: 12.0pt; font-family: 'Arial',sans-serif; mso-fareast-font-family: 'Times New Roman'; color: #404040;\">Input Voltage (limits)</span></p>\n<p class=\"MsoNormal\" style=\"margin-bottom: 7.5pt; line-height: normal;\"><span style=\"font-size: 12.0pt; font-family: 'Arial',sans-serif; mso-fareast-font-family: 'Times New Roman'; color: #404040;\">6-20V</span></p>\n<p class=\"MsoNormal\" style=\"margin-bottom: 7.5pt; line-height: normal;\"><span style=\"font-size: 12.0pt; font-family: 'Arial',sans-serif; mso-fareast-font-family: 'Times New Roman'; color: #404040;\">Digital I/O Pins</span></p>\n<p class=\"MsoNormal\" style=\"margin-bottom: 7.5pt; line-height: normal;\"><span style=\"font-size: 12.0pt; font-family: 'Arial',sans-serif; mso-fareast-font-family: 'Times New Roman'; color: #404040;\">54 (of which 14 provide PWM output)</span></p>\n<p class=\"MsoNormal\" style=\"margin-bottom: 7.5pt; line-height: normal;\"><span style=\"font-size: 12.0pt; font-family: 'Arial',sans-serif; mso-fareast-font-family: 'Times New Roman'; color: #404040;\">Analog Input Pins</span></p>\n<p class=\"MsoNormal\" style=\"margin-bottom: 7.5pt; line-height: normal;\"><span style=\"font-size: 12.0pt; font-family: 'Arial',sans-serif; mso-fareast-font-family: 'Times New Roman'; color: #404040;\">16</span></p>\n<p class=\"MsoNormal\" style=\"margin-bottom: 7.5pt; line-height: normal;\"><span style=\"font-size: 12.0pt; font-family: 'Arial',sans-serif; mso-fareast-font-family: 'Times New Roman'; color: #404040;\">DC Current per I/O Pin</span></p>\n<p class=\"MsoNormal\" style=\"margin-bottom: 7.5pt; line-height: normal;\"><span style=\"font-size: 12.0pt; font-family: 'Arial',sans-serif; mso-fareast-font-family: 'Times New Roman'; color: #404040;\">40 mA</span></p>\n<p class=\"MsoNormal\" style=\"margin-bottom: 7.5pt; line-height: normal;\"><span style=\"font-size: 12.0pt; font-family: 'Arial',sans-serif; mso-fareast-font-family: 'Times New Roman'; color: #404040;\">DC Current for 3.3V Pin</span></p>\n<p class=\"MsoNormal\" style=\"margin-bottom: 7.5pt; line-height: normal;\"><span style=\"font-size: 12.0pt; font-family: 'Arial',sans-serif; mso-fareast-font-family: 'Times New Roman'; color: #404040;\">50 mA</span></p>\n<p class=\"MsoNormal\" style=\"margin-bottom: 7.5pt; line-height: normal;\"><span style=\"font-size: 12.0pt; font-family: 'Arial',sans-serif; mso-fareast-font-family: 'Times New Roman'; color: #404040;\">Flash Memory</span></p>\n<p class=\"MsoNormal\" style=\"margin-bottom: 7.5pt; line-height: normal;\"><span style=\"font-size: 12.0pt; font-family: 'Arial',sans-serif; mso-fareast-font-family: 'Times New Roman'; color: #404040;\">256 KB of which 8 KB used by bootloader</span></p>\n<p class=\"MsoNormal\" style=\"margin-bottom: 7.5pt; line-height: normal;\"><span style=\"font-size: 12.0pt; font-family: 'Arial',sans-serif; mso-fareast-font-family: 'Times New Roman'; color: #404040;\">SRAM</span></p>\n<p class=\"MsoNormal\" style=\"margin-bottom: 7.5pt; line-height: normal;\"><span style=\"font-size: 12.0pt; font-family: 'Arial',sans-serif; mso-fareast-font-family: 'Times New Roman'; color: #404040;\">8 KB</span></p>\n<p class=\"MsoNormal\" style=\"margin-bottom: 7.5pt; line-height: normal;\"><span style=\"font-size: 12.0pt; font-family: 'Arial',sans-serif; mso-fareast-font-family: 'Times New Roman'; color: #404040;\">EEPROM</span></p>\n<p class=\"MsoNormal\" style=\"margin-bottom: 7.5pt; line-height: normal;\"><span style=\"font-size: 12.0pt; font-family: 'Arial',sans-serif; mso-fareast-font-family: 'Times New Roman'; color: #404040;\">4 KB</span></p>\n<p class=\"MsoNormal\" style=\"margin-bottom: 7.5pt; line-height: normal;\"><span style=\"font-size: 12.0pt; font-family: 'Arial',sans-serif; mso-fareast-font-family: 'Times New Roman'; color: #404040;\">Clock Speed</span></p>\n<p class=\"MsoNormal\" style=\"margin-bottom: 7.5pt; line-height: normal;\"><span style=\"font-size: 12.0pt; font-family: 'Arial',sans-serif; mso-fareast-font-family: 'Times New Roman'; color: #404040;\">16 MHz</span></p>\n<p class=\"MsoNormal\" style=\"margin-bottom: 7.5pt; line-height: normal;\"><span style=\"font-size: 12.0pt; font-family: 'Arial',sans-serif; mso-fareast-font-family: 'Times New Roman'; color: #404040;\"> </span></p>\n<p class=\"MsoNormal\"><span style=\"font-size: 12.0pt; line-height: 107%; font-family: 'Arial',sans-serif;\"> </span></p>",
      "en_main_category": "Arduino",
      "ar_main_category": "Arduino",
      "en_category": "Arduino",
      "ar_category": "Arduino",
      "price": 7,
      "image": "https://zfloos-production-storage.s3.eu-central-1.amazonaws.com/public/upload/companies/4247/products/217349474226769325e1e50c9_95100865.jpg,https://zfloos-production-storage.s3.eu-central-1.amazonaws.com/public/upload/companies/4247/products/2173494741767693259e26ee9_66400617.jpg,https://zfloos-production-storage.s3.eu-central-1.amazonaws.com/public/upload/companies/4247/products/017349474196769325bba8b03_06950500.jpg",
      "quantity_on_hand": 20,
      "sold_quantity": 0,
      "visible_in_catalog": 1,
      "visible_in_search": 1,
      "slug_url": "https://amtronics.co/products/arduino-mega-2560-2064643",
      "discount": 0,
      // "discount_type": null,
      // "ar_brand": null,
      // "en_brand": null,
      "ave_cost": 6.201
    },
    {
      "_id": "6837f9ab571e0fa754eb5c6e",
      "id": 2065600,
      "sku": "4010",
      "en_name": "DHT 11 Temperature And Humidity Sensor",
      "ar_name": "DHT 11 Temperature And Humidity Sensor",
      "en_description": "DHT 11 Temperature And Humidity Sensor",
      "ar_description": "DHT 11 Temperature And Humidity Sensor",
      "en_long_description": "<div class=\"MsoNormal\" style=\"text-align: center;\" align=\"center\"><hr style=\"color: #a0a0a0;\" align=\"center\" noshade=\"noshade\" size=\"0\" width=\"100%\" /></div>\n<h2 style=\"box-sizing: border-box; font-variant-ligatures: normal; font-variant-caps: normal; orphans: 2; text-align: start; widows: 2; -webkit-text-stroke-width: 0px; text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial; word-spacing: 0px; margin: 15.0pt 0in 7.5pt 0in;\"><span style=\"font-size: 12.0pt; font-family: 'Arial',sans-serif; color: #404040; font-weight: normal;\">Product Description</span></h2>\n<p style=\"box-sizing: border-box; font-variant-ligatures: normal; font-variant-caps: normal; orphans: 2; text-align: start; widows: 2; -webkit-text-stroke-width: 0px; text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial; word-spacing: 0px; margin: 0in 0in 7.5pt 0in;\"><span class=\"a-text-bold\"><span style=\"box-sizing: border-box;\"><span style=\"font-family: 'Arial',sans-serif; color: #404040;\">The DHT11 humidity and temperature sensor makes it really easy to add humidity and temperature data to your DIY electronics projects. It's perfect for remote weather stations, home environmental control systems, and farm or garden monitoring systems.</span></span></span></p>\n<p style=\"box-sizing: border-box; font-variant-ligatures: normal; font-variant-caps: normal; orphans: 2; text-align: start; widows: 2; -webkit-text-stroke-width: 0px; text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial; word-spacing: 0px; margin: 0in 0in 7.5pt 0in;\"><span class=\"a-text-bold\"><span style=\"box-sizing: border-box;\"><span style=\"font-family: 'Arial',sans-serif; color: #404040;\"><span style=\"box-sizing: border-box;\">DHT11 Specifications:</span></span></span></span></p>\n<p style=\"box-sizing: border-box; font-variant-ligatures: normal; font-variant-caps: normal; orphans: 2; text-align: start; widows: 2; -webkit-text-stroke-width: 0px; text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial; word-spacing: 0px; margin: 0in 0in 7.5pt 0in;\"><span style=\"font-family: 'Arial',sans-serif; color:500; color: #404040;\"><span style=\"box-sizing: border-box;\">Operating Voltage: 3.5V to 5.5V</span></span></p>\n<p style=\"box-sizing: border-box; font-variant-ligatures: normal; font-variant-caps: normal; orphans: 2; text-align: start; widows: 2; -webkit-text-stroke-width: 0px; text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial; word-spacing: 0px; margin: 0in 0in 7.5pt 0in;\"><span style=\"font-family: 'Arial',sans-serif; color: #404040;\"><span style=\"box-sizing: border-box;\">Operating current: 0.3mA (measuring) 60uA (standby)</span></span></p>\n<p style=\"box-sizing: border-box; font-variant-ligatures: normal; font-variant-caps: normal; orphans: 2; text-align: start; widows: 2; -webkit-text-stroke-width: 0px; text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial; word-spacing: 0px; margin: 0in 0in 7.5pt 0in;\"><span style=\"font-family: 'Arial',sans-serif; color: #404040;\"><span style=\"box-sizing: border-box;\">Output: Serial data</span></span></p>\n<p style=\"box-sizing: border-box; font-variant-ligatures: normal; font-variant-caps: normal; orphans: 2; text-align: start; widows: 2; -webkit-text-stroke-width: 0px; text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial; word-spacing: 0px; margin: 0in 0in 7.5pt 0in;\"><span style=\"font-family: 'Arial',sans-serif; color: #404040;\"><span style=\"box-sizing: border-box;\">Temperature Range: 0°C to 50°C</span></span></p>\n<p style=\"box-sizing: border-box; font-variant-ligatures: normal; font-variant-caps: normal; orphans: 2; text-align: start; widows: 2; -webkit-text-stroke-width: 0px; text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial; word-spacing: 0px; margin: 0in 0in 7.5pt 0in;\"><span style=\"font-family: 'Arial',sans-serif; color: #404040;\"><span style=\"box-sizing: border-box;\">Humidity Range: 20% to 90%</span></span></p>\n<p style=\"box-sizing: border-box; font-variant-ligatures: normal; font-variant-caps: normal; orphans: 2; text-align: start; widows: 2; -webkit-text-stroke-width: 0px; text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial; word-spacing: 0px; margin: 0in 0in 7.5pt 0in;\"><span style=\"font-family: 'Arial',sans-serif; color: #404040;\"><span style=\"box-sizing: border-box;\">Resolution: Temperature and Humidity both are 16-bit</span></span></p>\n<p style=\"box-sizing: border-box; font-variant-ligatures: normal; font-variant-caps: normal; orphans: 2; text-align: start; widows: 2; -webkit-text-stroke-width: 0px; text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial; word-spacing: 0px; margin: 0in 0in 7.5pt 0in;\"><span style=\"font-family: 'Arial',sans-serif; color: #404040;\"><span style=\"box-sizing: border-box;\">Accuracy: ±1°C and ±1%</span></span></p>\n<p class=\"MsoNormal\" style=\"margin-bottom: 7.5pt; box-sizing: border-box; font-variant-ligatures: normal; font-variant-caps: normal; orphans: 2; text-align: start; widows: 2; -webkit-text-stroke-width: 0px; text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial; word-spacing: 0px;\"><span style=\"font-size: 12.0pt; line-height: 107%; font-family: 'Arial',sans-serif; color: #404040;\"><span style=\"box-sizing: border-box;\"> </span></span></p>\n<p class=\"MsoNormal\"><span style=\"font-size: 12.0pt; line-height: 107%; font-family: 'Arial',sans-serif;\"> </span></p>",
      "ar_long_description": "<div class=\"MsoNormal\" style=\"text-align: center;\" align=\"center\"><hr style=\"color: #a0a0a0;\" align=\"center\" noshade=\"noshade\" size=\"0\" width=\"100%\" /></div>\n<h2 style=\"box-sizing: border-box; font-variant-ligatures: normal; font-variant-caps: normal; orphans: 2; text-align: start; widows: 2; -webkit-text-stroke-width: 0px; text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial; word-spacing: 0px; margin: 15.0pt 0in 7.5pt 0in;\"><span style=\"font-size: 12.0pt; font-family: 'Arial',sans-serif; color: #404040; font-weight: normal;\">Product Description</span></h2>\n<p style=\"box-sizing: border-box; font-variant-ligatures: normal; font-variant-caps: normal; orphans: 2; text-align: start; widows: 2; -webkit-text-stroke-width: 0px; text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial; word-spacing: 0px; margin: 0in 0in 7.5pt 0in;\"><span class=\"a-text-bold\"><span style=\"box-sizing: border-box;\"><span style=\"font-family: 'Arial',sans-serif; color: #404040;\">The DHT11 humidity and temperature sensor makes it really easy to add humidity and temperature data to your DIY electronics projects. It's perfect for remote weather stations, home environmental control systems, and farm or garden monitoring systems.</span></span></span></p>\n<p style=\"box-sizing: border-box; font-variant-ligatures: normal; font-variant-caps: normal; orphans: 2; text-align: start; widows: 2; -webkit-text-stroke-width: 0px; text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial; word-spacing: 0px; margin: 0in 0in 7.5pt 0in;\"><span class=\"a-text-bold\"><span style=\"box-sizing: border-box;\"><span style=\"font-family: 'Arial',sans-serif; color: #404040;\"><span style=\"box-sizing: border-box;\">DHT11 Specifications:</span></span></span></span></p>\n<p style=\"box-sizing: border-box; font-variant-ligatures: normal; font-variant-caps: normal; orphans: 2; text-align: start; widows: 2; -webkit-text-stroke-width: 0px; text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial; word-spacing: 0px; margin: 0in 0in 7.5pt 0in;\"><span style=\"font-family: 'Arial',sans-serif; color: #404040;\"><span style=\"box-sizing: border-box;\">Operating Voltage: 3.5V to 5.5V</span></span></p>\n<p style=\"box-sizing: border-box; font-variant-ligatures: normal; font-variant-caps: normal; orphans: 2; text-align: start; widows: 2; -webkit-text-stroke-width: 0px; text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial; word-spacing: 0px; margin: 0in 0in 7.5pt 0in;\"><span style=\"font-family: 'Arial',sans-serif; color: #404040;\"><span style=\"box-sizing: border-box;\">Operating current: 0.3mA (measuring) 60uA (standby)</span></span></p>\n<p style=\"box-sizing: border-box; font-variant-ligatures: normal; font-variant-caps: normal; orphans: 2; text-align: start; widows: 2; -webkit-text-stroke-width: 0px; text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial; word-spacing: 0px; margin: 0in 0in 7.5pt 0in;\"><span style=\"font-family: 'Arial',sans-serif; color: #404040;\"><span style=\"box-sizing: border-box;\">Output: Serial data</span></span></p>\n<p style=\"box-sizing: border-box; font-variant-ligatures: normal; font-variant-caps: normal; orphans: 2; text-align: start; widows: 2; -webkit-text-stroke-width: 0px; text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial; word-spacing: 0px; margin: 0in 0in 7.5pt 0in;\"><span style=\"font-family: 'Arial',sans-serif; color: #404040;\"><span style=\"box-sizing: border-box;\">Temperature Range: 0°C to 50°C</span></span></p>\n<p style=\"box-sizing: border-box; font-variant-ligatures: normal; font-variant-caps: normal; orphans: 2; text-align: start; widows: 2; -webkit-text-stroke-width: 0px; text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial; word-spacing: 0px; margin: 0in 0in 7.5pt 0in;\"><span style=\"font-family: 'Arial',sans-serif; color: #404040;\"><span style=\"box-sizing: border-box;\">Humidity Range: 20% to 90%</span></span></p>\n<p style=\"box-sizing: border-box; font-variant-ligatures: normal; font-variant-caps: normal; orphans: 2; text-align: start; widows: 2; -webkit-text-stroke-width: 0px; text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial; word-spacing: 0px; margin: 0in 0in 7.5pt 0in;\"><span style=\"font-family: 'Arial',sans-serif; color: #404040;\"><span style=\"box-sizing: border-box;\">Resolution: Temperature and Humidity both are 16-bit</span></span></p>\n<p style=\"box-sizing: border-box; font-variant-ligatures: normal; font-variant-caps: normal; orphans: 2; text-align: start; widows: 2; -webkit-text-stroke-width: 0px; text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial; word-spacing: 0px; margin: 0in 0in 7.5pt 0in;\"><span style=\"font-family: 'Arial',sans-serif; color: #404040;\"><span style=\"box-sizing: border-box;\">Accuracy: ±1°C and ±1%</span></span></p>\n<p class=\"MsoNormal\" style=\"margin-bottom: 7.5pt; box-sizin g: border-box; font-variant-ligatures: normal; font-variant-caps: normal; orphans: 2; text-align: start; widows: 2; -webkit-text-stroke-width: 0px; text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial; word-spacing: 0px;\"><span style=\"font-size: 12.0pt; line-height: 107%; font-family: 'Arial',sans-serif; color: #404040;\"><span style=\"box-sizing: border-box;\"> </span></span></p>\n<p class=\"MsoNormal\"><span style=\"font-size: 12.0pt; line-height: 107%; font-family: 'Arial',sans-serif;\"> </span></p>",
      "en_main_category": "Sensor",
      "ar_main_category": "Sensor",
      "en_category": "Sensor",
      "ar_category": "Sensor",
      "price": 0.75,
      "image": "https://zfloos-production-storage.s3.eu-central-1.amazonaws.com/public/upload/companies/4247/products/11735060178676aead2abc349_12754880.jpg",
      "quantity_on_hand": 105,
      "sold_quantity": 5,
      "visible_in_catalog": 1,
      "visible_in_search": 1,
      "slug_url": "https://amtronics.co/products/dht-11-temperature-and-humidity-sensor-2065600",
      "discount": 0,
      // "discount_type": null,
      // "ar_brand": null,
      // "en_brand": null,
      "ave_cost": 0.338
    },
    {
      "_id": "6837f9ab571e0fa754eb5bd7",
      "id": 2067963,
      "sku": "19008",
      "en_name": "Servo Motor SG90 180°",
      "ar_name": "Servo Motor SG90 180°",
      "en_description": "Servo Motor SG90 180°",
      "ar_description": "Servo Motor SG90 180°",
      "en_long_description": "<h2 style=\"margin: 15.0pt 0in 7.5pt 0in;\"><span style=\"font-size: 12.0pt; font-family: 'Arial',sans-serif; color: #404040; font-weight: normal;\"><br />Product description</span></h2>\n<p style=\"box-sizing: border-box; font-variant-ligatures: normal; font-variant-caps: normal; orphans: 2; text-align: start; widows: 2; -webkit-text-stroke-width: 0px; text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial; word-spacing: 0px; margin: 0in 0in 7.5pt 0in;\"><span style=\"font-family: 'Arial',sans-serif; color: #404040;\">Description:<br style=\"box-sizing: border-box;\" />DIYmall SG90 is a high quality,low-cost servo for all your mechatronic needs. It comes with a 3-pin power and control cable, mounting hardware.<br style=\"box-sizing: border-box;\" /><br style=\"box-sizing: border-box;\" />Circuit connection:<br style=\"box-sizing: border-box;\" />Yellow line (signal line)<br style=\"box-sizing: border-box;\" />Red line (power line)<br style=\"box-sizing: border-box;\" />Brown (ground)<br style=\"box-sizing: border-box;\" /><br style=\"box-sizing: border-box;\" />Speed: Standard speed is 120 degrees, the maximum speed is 180 degrees<br style=\"box-sizing: border-box;\" />Operating Voltage : 4.8~6.0V<br style=\"box-sizing: border-box;\" />Currenct: 0.19A@5V</span><span style=\"box-sizing: border-box;\"><span style=\"font-family: 'MS Gothic'; mso-ascii-font-family: Arial; mso-hansi-font-family: Arial; mso-bidi-font-family: Arial; color: #404040;\">，</span></span><span style=\"box-sizing: border-box;\"><span style=\"font-family: 'Arial',sans-serif; color: #404040;\">0.24A@6V<br style=\"box-sizing: border-box;\" />Operating Speed : 0.12sec/60 degree(4.8V)~0.1sec/60 degree(6.0V)<br style=\"box-sizing: border-box;\" />Torque : 1.6kg/cm(4.8V)<br style=\"box-sizing: border-box;\" />Dead Band Width : 5usec<br style=\"box-sizing: border-box;\" />Temperature Range : -30~+60</span></span><span style=\"box-sizing: border-box;\"><span style=\"font-family: 'Cambria Math',serif; mso-bidi-font-family: 'Cambria Math'; color: #404040;\">℃</span></span><span style=\"box-sizing: border-box;\"><span style=\"font-family: 'Arial',sans-serif; color: #404040;\"><br style=\"box-sizing: border-box;\" />Cable Length : 25cm<br style=\"box-sizing: border-box;\" />Servo Type : Analog Servo</span></span></p>\n<p class=\"MsoNormal\" style=\"margin-bottom: 7.5pt; box-sizing: border-box; font-variant-ligatures: normal; font-variant-caps: normal; orphans: 2; text-align: start; widows: 2; -webkit-text-stroke-width: 0px; text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial; word-spacing: 0px;\"><span style=\"font-size: 12.0pt; line-height: 107%; font-family: 'Arial',sans-serif; color: #404040;\"><span style=\"box-sizing: border-box;\"> </span></span></p>\n<p class=\"MsoNormal\"><span style=\"font-size: 12.0pt; line-height: 107%; font-family: 'Arial',sans-serif;\"> </span></p>",
      "ar_long_description": "<h2 style=\"margin: 15.0pt 0in 7.5pt 0in;\"><span style=\"font-size: 12.0pt; font-family: 'Arial',sans-serif; color: #404040; font-weight: normal;\"><br />Product description</span></h2>\n<p style=\"box-sizing: border-box; font-variant-ligatures: normal; font-variant-caps: normal; orphans: 2; text-align: start; widows: 2; -webkit-text-stroke-width: 0px; text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial; word-spacing: 0px; margin: 0in 0in 7.5pt 0in;\"><span style=\"font-family: 'Arial',sans-serif; color: #404040;\">Description:<br style=\"box-sizing: border-box;\" />DIYmall SG90 is a high quality,low-cost servo for all your mechatronic needs. It comes with a 3-pin power and control cable, mounting hardware.<br style=\"box-sizing: border-box;\" /><br style=\"box-sizing: border-box;\" />Circuit connection:<br style=\"box-sizing: border-box;\" />Yellow line (signal line)<br style=\"box-sizing: border-box;\" />Red line (power line)<br style=\"box-sizing: border-box;\" />Brown (ground)<br style=\"box-sizing: border-box;\" /><br style=\"box-sizing: border-box;\" />Speed: Standard speed is 120 degrees, the maximum speed is 180 degrees<br style=\"box-sizing: border-box;\" />Operating Voltage : 4.8~6.0V<br style=\"box-sizing: border-box;\" />Currenct: 0.19A@5V</span><span style=\"box-sizing: border-box;\"><span style=\"font-family: 'MS Gothic'; mso-ascii-font-family: Arial; mso-hansi-font-family: Arial; mso-bidi-font-family: Arial; color: #404040;\">，</span></span><span style=\"box-sizing: border-box;\"><span style=\"font-family: 'Arial',sans-serif; color: #404040;\">0.24A@6V<br style=\"box-sizing: border-box;\" />Operating Speed : 0.12sec/60 degree(4.8V)~0.1sec/60 degree(6.0V)<br style=\"box-sizing: border-box;\" /> torque : 1.6kg/cm(4.8V)<br style=\"box-sizing: border-box;\" />Dead Band Width : 5usec<br style=\"box-sizing: border-box;\" />Temperature Range : -30~+60</span></span><span style=\"box-sizing: border-box;\"><span style=\"font-family: 'Cambria Math',serif; mso-bidi-font-family: 'Cambria Math'; color: #404040;\">℃</span></span><span style=\"box-sizing: border-box;\"><span style=\"font-family: 'Arial',sans-serif; color: #404040;\"><br style=\"box-sizing: border-box;\" />Cable Length : 25cm<br style=\" koh-sizing: border-box;\" />Servo Type : Analog Servo</span></span></p>\n<p class=\"MsoNormal\" style=\"margin-bottom: 7.5pt; box-sizing: border-box; font-variant-ligatures: normal; font-variant-caps: normal; orphans: 2; text-align: start; widows: 2; -webkit-text-stroke-width: 0px; text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial; word-spacing: 0px;\"><span style=\"font-size: 12.0pt; line-height: 107%; font-family: 'Arial',sans-serif; color: #404040;\"><span style=\"box-sizing: border-box;\"> </span></span></p>\n<p class=\"MsoNormal\"><span style=\"font-size: 12.0pt; line-height: 107%; font-family: 'Arial',sans-serif;\"> </span></p>",
      "en_main_category": "Motor",
      "ar_main_category": "Motor",
      "en_category": "Motor,Servo & Stepper Motor",
      "ar_category": "Motor,Servo & Stepper Motor",
      "price": 1,
      "image": "https://zfloos-production-storage.s3.eu-central-1.amazonaws.com/public/upload/companies/4247/products/91735235773676d98bd0aea65_83000673.jpg,https://zfloos-production-storage.s3.eu-central-1.amazonaws.com/public/upload/companies/4247/products/01735235784676d98c8ac7db1_61453310.jpg,https://zfloos-production-storage.s3.eu-central-1.amazonaws.com/public/upload/companies/4247/products/61735235771676d98bbd16795_87868860.jpg,https://zfloos-production-storage.s3.eu-central-1.amazonaws.com/public/upload/companies/4247/products/81735235772676d98bc7155b5_17945870.jpg",
      "quantity_on_hand": 107,
      "sold_quantity": 3,
      "visible_in_catalog": 1,
      "visible_in_search": 1,
      "slug_url": "https://amtronics.co/products/servo-motor-sg90-180-2067963",
      "discount": 0,
      // "discount_type": null,
      // "ar_brand": null,
      // "en_brand": null,
      "ave_cost": 0.735
    },
    {
      "_id": "6837f9ab571e0fa754eb5c0b",
      "id": 2067877,
      "sku": "8021",
      "en_name": "OLED Display 0.96 inch I2C",
      "ar_name": "شاشة OLED 0.96 بوصة I2C",
      "en_description": "Compact screen for projects.",
      "ar_description": "شاشة صغيرة للمشاريع.",
      "en_long_description": "128x64 pixels, ideal for microcontroller displays.",
      "ar_long_description": "دقة 128x64 بكسل، مثالية للشاشات الصغيرة.",
      "en_main_category": "Displays",
      "ar_main_category": "شاشات",
      "en_category": "OLED",
      "ar_category": "OLED",
      "price": 4.5,
      "image": "https://zfloos-production-storage.s3.eu-central-1.amazonaws.com/public/upload/companies/4247/products/11735210588676d365c9bb3e8_62712965.jpg,https://zfloos-production-storage.s3.eu-central-1.amazonaws.com/public/upload/companies/4247/products/41735210587676d365bcf13b5_12062825.jpg",
      "quantity_on_hand": 60,
      "sold_quantity": 101,
      "visible_in_catalog": 1,
      "visible_in_search": 1,
      "slug_url": "oled-i2c-0-96",
      "en_brand": "Generic",
      "ar_brand": "عام",
      "ave_cost": 3.1
    },
    {
      "_id": "6837f9ab571e0fa754eb5bf7",
      "id": 2067899,
      "sku": "1022",
      "en_name": "Buzzer Module 5V Active",
      "ar_name": "وحدة صفارة 5 فولت نشطة",
      "en_description": "Makes sound when powered.",
      "ar_description": "تنتج صوتًا عند التشغيل.",
      "en_long_description": "Great for alerts in electronic projects.",
      "ar_long_description": "ممتازة للتنبيهات في المشاريع الإلكترونية.",
      "en_main_category": "Modules",
      "ar_main_category": "وحدات",
      "en_category": "Sound",
      "ar_category": "صوت",
      "price": 1.15,
      "image": "https://zfloos-production-storage.s3.eu-central-1.amazonaws.com/public/upload/companies/4247/products/91735212167676d3c87b55aa3_11400405.jpg,https://zfloos-production-storage.s3.eu-central-1.amazonaws.com/public/upload/companies/4247/products/81735212168676d3c8828e663_73495882.jpg,https://zfloos-production-storage.s3.eu-central-1.amazonaws.com/public/upload/companies/4247/products/41735212169676d3c8912df74_92849890.jpg,https://zfloos-production-storage.s3.eu-central-1.amazonaws.com/public/upload/companies/4247/products/41735212169676d3c89c9ee18_35094034.jpg",
      "quantity_on_hand": 95,
      "sold_quantity": 86,
      "visible_in_catalog": 1,
      "visible_in_search": 1,
      "slug_url": "active-buzzer-module",
      "en_brand": "Keyes",
      "ar_brand": "كييز",
      "ave_cost": 0.75
    },
    // {
    //   "_id": "2067643",
    //   "id": 2067643,
    //   "sku": "6040",
    //   "en_name": "HC-SR04 Ultrasonic Sensor",
    //   "ar_name": "حساس الموجات فوق الصوتية HC-SR04",
    //   "en_description": "Distance measuring sensor.",
    //   "ar_description": "حساس قياس المسافة.",
    //   "en_long_description": "Used in robotics, automation, and security.",
    //   "ar_long_description": "يُستخدم في الروبوتات والتطبيقات الأمنية.",
    //   "en_main_category": "Sensors",
    //   "ar_main_category": "حساسات",
    //   "en_category": "Distance",
    //   "ar_category": "مسافة",
    //   "price": 2.25,
    //   "image": "/placeholder.svg",
    //   "quantity_on_hand": 78,
    //   "sold_quantity": 133,
    //   "visible_in_catalog": 1,
    //   "visible_in_search": 1,
    //   "slug_url": "ultrasonic-hcsr04",
    //   "en_brand": "HC",
    //   "ar_brand": "إتش سي",
    //   "ave_cost": 1.5
    // }
  ]
}